apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.5
  interval: 1m0s
  values:
    controller:
      service:
        loadBalancerIP: 1.2.3.4
      admissionWebhooks:
        enabled: false
