apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - blue-deploy.yaml
  - green-deploy.yaml
  - ingress.yaml
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
